# Generated by Django 5.1.2 on 2024-10-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nom_animal', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('num_identification', models.CharField(max_length=50)),
                ('primo_vacc', models.DateField()),
                ('rappel_vacc', models.DateField()),
                ('vermifuge', models.DateField()),
                ('antipuce', models.DateField()),
                ('sterilise', models.DateField()),
                ('biberonnage', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
    ]
