# Generated by Django 5.1.2 on 2024-10-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='biberonnage',
        ),
        migrations.AlterField(
            model_name='animal',
            name='biberonnage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sterilise',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
