# Generated by Django 5.1.2 on 2024-10-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA',
            fields=[
                ('id_fa', models.AutoField(primary_key=True, serialize=False)),
                ('prenom_fa', models.CharField(max_length=100)),
                ('libelle_facebook', models.CharField(max_length=100)),
                ('libelle_veterinaire', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id_statut', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_statut', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='num_identification',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
