# Generated by Django 5.1.2 on 2024-10-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fa_statut_alter_animal_num_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_categoie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id_provenance', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_provenance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sexe',
            fields=[
                ('id_sexe', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_sexe', models.CharField(max_length=100)),
            ],
        ),
    ]
