# Generated by Django 5.1.2 on 2024-10-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_archive_biberonnage_alter_animal_biberonnage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fa',
            name='libelle_facebook',
        ),
        migrations.AddField(
            model_name='fa',
            name='commune_fa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fa',
            name='libelle_reseausociaux',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fa',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fa',
            name='telephone_fa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fa',
            name='libelle_veterinaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fa',
            name='prenom_fa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
