# Generated by Django 5.0.1 on 2024-11-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_libelle_categoie_categorie_libelle_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='fa',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='note',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='statut',
        ),
        migrations.AlterField(
            model_name='archive',
            name='sterilise',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
