# Generated by Django 5.1.2 on 2024-10-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_animal_statut_alter_animal_antipuce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categorie'),
        ),
        migrations.AddField(
            model_name='animal',
            name='fa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fa'),
        ),
        migrations.AddField(
            model_name='animal',
            name='provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.provenance'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sexe'),
        ),
    ]
