# Generated by Django 5.0.1 on 2024-11-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_archive_fa_remove_archive_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='antipuce',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='sterilise',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='vermifuge',
        ),
    ]
