# Generated by Django 5.1.2 on 2024-10-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_animal_categorie_animal_fa_animal_provenance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nom_animal', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('num_identification', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('primo_vacc', models.DateField(blank=True, null=True)),
                ('rappel_vacc', models.DateField(blank=True, null=True)),
                ('vermifuge', models.DateField(blank=True, null=True)),
                ('antipuce', models.DateField(blank=True, null=True)),
                ('sterilise', models.DateField(blank=True, null=True)),
                ('biberonnage', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categorie')),
                ('fa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fa')),
                ('provenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.provenance')),
                ('sexe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sexe')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.statut')),
            ],
        ),
    ]
