# Generated by Django 5.0.1 on 2024-11-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_archive_antipuce_remove_archive_sterilise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='antipuce',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='vermifuge',
            field=models.DateField(blank=True, null=True),
        ),
    ]
