# Generated by Django 5.1.2 on 2024-11-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_id_archive_archive_id_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='biberonnage',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='images',
        ),
    ]
