# Generated by Django 5.1.2 on 2024-11-20 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_archive_biberonnage_remove_archive_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='archived_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
