# Generated by Django 5.1.2 on 2024-11-20 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_archive_archived_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='archived_at',
        ),
        migrations.AddField(
            model_name='archive',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
