# Generated by Django 5.1.2 on 2024-11-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_animal_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='created_at',
        ),
    ]
