# Generated by Django 5.1.2 on 2024-11-20 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_animal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='date_arrivee',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
