# Generated by Django 5.1.2 on 2024-11-22 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_animal_date_arrivee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='images',
        ),
        migrations.RemoveField(
            model_name='image',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AddField(
            model_name='image',
            name='animal_reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='api.animal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
