# Generated by Django 5.0.1 on 2024-12-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_animal_images_remove_image_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa',
            name='email_fa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
